name: rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: running cargo check
        run: ./.github/workflows/rust.sh $napi $flags
        env:
          napi: "1,2,3,4,5,6,experimental"
          # format of a flag in "flags" is-
          # <flag_name>:<min_napi_version> or <flag_name>
          flags: "proc-macros,try-catch-api,channel-api:4"
