name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          napi: [1,2,3,4,5,6,experimental]
          #default run with no feature flags
          feature-flag: [no-ff]
          include:
           - napi: 1
             feature-flag: proc-macros
           - napi: 1
             feature-flag: try-catch-api
           - napi: 4
             feature-flag: channel-api
           - napi: 6
             feature-flag: channel-api
    steps:
      - if: matrix.feature-flag == 'no-ff'
        name: running cargo check with no feature flag
        run: echo "run cargo check with no feature flag"
      - name: running cargo check with a feature flag
        if: matrix.feature-flag != 'no-ff'
        run: echo "run cargo check with feature flag" ${{matrix.feature-flag}}
