name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node: [8, 10, 12, 14]
          include:
        # excludes node 8 on macOS
           -  node: 8
              exp: trues
           - os: ubuntu-18.04
             node: LTS
    steps:
      - name: Echo site details
        run: echo ${{matrix.os}} ${{matrix.node}}
      - name: extra step
        if: matrix.exp
        run: echo running ${{matrix.os}} ${{matrix.node}}
      - name: Every time
        run: echo "This step will always run"
