name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          os: [macos-latest, windows-latest, ubuntu-18.04]
          node: [8, 10, 12, 14]
          include:
        # excludes node 8 on macOS
           - os: macos-latest
             node: 8
             exp: true
    steps:
      - name: Echo site details
        run: echo ${{matrix.os}} ${{matrix.node}}
      - name: extra step
        if: matrix.exp == true
        run: echo running ${{matrix.os}} ${{matrix.node}}
