name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          napi: [1,2,3,4,5,6,experimental]
          #default run with no feature flags
          feature-flag: [no-ff]
          include:
           - napi: 1
             feature-flag: 1
           - napi: 1
             feature-flag: 2
    steps:
      - if: matrix.exp == 'no-ff'
        name: run cargo check with no feature flag
        run: echo "run cargo check with no feature flag"
      - name: run cargo check with a feature flag
        if: matrix.exp != 'no-ff'
        run: echo "run cargo check with a feature flag"
